/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;

/**
 *
 * @author glSon8840
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        buttonStart = new javax.swing.JButton();
        buttonHow = new javax.swing.JButton();
        buttonInfo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        TitleLabel.setText("????????????????????");

        buttonStart.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        buttonHow.setText("How");
        buttonHow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHowActionPerformed(evt);
            }
        });

        buttonInfo.setText("Information");
        buttonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonInfo)
                                .addComponent(buttonHow, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonStart)
                .addGap(39, 39, 39)
                .addComponent(buttonHow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(buttonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        //new panel
        new ModeOption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonHowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHowActionPerformed
        //new panel
        new Instruction().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonHowActionPerformed

    private void buttonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoActionPerformed
        //new panel
        new Information().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonInfoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //exit
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public class Board {
    public static final int WINDOW_WIDTH = 1000;
    public static final int WINDOW_HEIGHT = 800;
    public static void main(String args[]) throws IOException{ 
        System.out.println("Working Directory = " +  System.getProperty("user.dir"));
        String[] Chapter = {"Cells","Genetics","Circulation & Digestion & Respiration","Plants","Diversity of living things", "Evolution" };
        JFrame frame = new JFrame("Jeopardy!");
        frame.setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        int width  = 6;
        int height = 6;
        int l,m,n;
        String Qestio,Answe,Section;
        String[][] Question=new String[height][width];
        String[][] Answer=new String[height][width];
        JButton[] categories = new JButton[width];
        for (int i = 0; i < width; i++) {
            categories[i] = new JButton(Chapter[i]);
            categories[i].setSize(WINDOW_WIDTH / width - 4, 20);
        }
        JButton[][] BLK = new JButton[height][width];
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                BLK[i][j] = new JButton("Level" + i);
                JBox.setSize(BLK[i][j], WINDOW_WIDTH / width - 4,
                        WINDOW_HEIGHT / height - 36);
                BLK[i][j].setBackground(Color.BLUE);
                BLK[i][j].setForeground(Color.YELLOW);
                BLK[i][j].setBorder(BorderFactory.createRaisedBevelBorder());
                BLK[i][j].setFont(new Font("DejaVu Serif", Font.BOLD, 32));
                
            }
        }
        JBox board =
                JBox.vbox(
                        JBox.hbox(categories[0],categories[1],categories[2],categories[3],categories[4],categories[5]),
                        JBox.hbox(BLK[0][0], BLK[0][1], BLK[0][2], BLK[0][3],BLK[0][4], BLK[0][5]),
                        JBox.hbox(BLK[1][0], BLK[1][1], BLK[1][2], BLK[1][3],BLK[1][4], BLK[1][5]),
                        JBox.hbox(BLK[2][0], BLK[2][1], BLK[2][2], BLK[2][3],BLK[2][4], BLK[2][5]),
                        JBox.hbox(BLK[3][0], BLK[3][1], BLK[3][2], BLK[3][3],BLK[3][4], BLK[3][5]),
                        JBox.hbox(BLK[4][0], BLK[4][1], BLK[4][2], BLK[4][3],BLK[4][4], BLK[4][5]),
                        JBox.hbox(BLK[5][0], BLK[5][1], BLK[5][2], BLK[5][3],BLK[5][4], BLK[5][5])
                );
        board.setSize(WINDOW_WIDTH - 20, WINDOW_HEIGHT);
        frame.add(board);
        frame.setVisible(true);

        //Read file
        final BufferedReader reader = new BufferedReader(new FileReader("Question.txt"));
        final ArrayList<String> lines = new ArrayList<String>();
        String s;
        String S;
        S="";
        while ((s = reader.readLine()) != null) {
            S=S+s;
        }
        reader.close();
        
        for ( int i = 0; i < height; i++) {
            l=S.indexOf(Chapter[i]);
            if(i<5)
            {
                m=S.indexOf(Chapter[i+1]);
                Section=S.substring(l,m);
            }
            else
            {
                Section=S.substring(l,S.length());
            }
            for (int  j = 0; j < width; j++) {
                l=Section.indexOf(String.valueOf(j+1)+". ");
                m=Section.indexOf("a. ",1);
                Qestio=Section.substring(l+3, m);
                Question[i][j]=Qestio;
                Section=Section.substring(m,Section.length());
                
                n=Section.indexOf("()",1);
                Answe=Section.substring(2,n);
                Answer[i][j]=Answe;
            }
        }
        for ( int i = 0; i < height; i++) {
            for (int  j = 0; j < width; j++) {
                String cd=Question[i][j];
                String ab=Answer[i][j];
                BLK[i][j].addActionListener(new ActionListener() {
                    @Override

                    public void actionPerformed(ActionEvent e) {
                        String your_answer = JOptionPane.showInputDialog(cd);
                        JOptionPane.showMessageDialog(null, "Reference and yours: "+ ab +" Vs " + your_answer);
                        JButton source = (JButton) e.getSource();
                        source.setEnabled(false);
                        source.setBackground(Color.GREEN);
                    }
                });
            }
        }
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
}
// PUT YOUR METHODS HERE
    
    
//    public static void Readfile() throws IOException {
//        ArrayList<String> quotes = new ArrayList<String>();
//        BufferedReader readFile = new BufferedReader(new FileReader("Question.txt"));
//        String line = "";
//    }
//    
//    public static void ButtonArray(){
//        JButton[][] buttons = new JButton[6][6];
//        
//        for(int i = 0; i < buttons.length; i++){
//            for(int j=0; j<buttons[i].length; j++){
//                buttons[i][j] = new JButton("Button [" + i + "][" + j + "]");
//            }
//        }
//    }
//    
//    public static boolean Answer(boolean Aw){
//       return Aw; 
//    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton buttonHow;
    private javax.swing.JButton buttonInfo;
    private javax.swing.JButton buttonStart;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
