/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.*;

/**
 *
 * @author glSon8840
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        TitleLabel.setText("????????????????????");

        jButton1.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addComponent(jButton2)
                .addGap(59, 59, 59)
                .addComponent(jButton3)
                .addGap(60, 60, 60)
                .addComponent(jButton4)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public class Board {
    public static final int WINDOW_WIDTH = 1000;
    public static final int WINDOW_HEIGHT = 800;
    public static void main(String args[]) throws IOException{ 
        System.out.println("Working Directory = " +  System.getProperty("user.dir"));
        String[] Chapter = {"Cells","Genetics","Circulation & Digestion & Respiration","Plants","Diversity of living things", "Evolution" };
        JFrame frame = new JFrame("Jeopardy!");
        frame.setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        int width  = 6;
        int height = 6;
        int l,m,n;
        String Qestio,Answe,Section;
        String[][] Question=new String[height][width];
        String[][] Answer=new String[height][width];
        JButton[] categories = new JButton[width];
        for (int i = 0; i < width; i++) {
            categories[i] = new JButton(Chapter[i]);
            categories[i].setSize(WINDOW_WIDTH / width - 4, 20);
        }
        JButton[][] BLK = new JButton[height][width];
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                BLK[i][j] = new JButton("Level" + i);
                JBox.setSize(BLK[i][j], WINDOW_WIDTH / width - 4,
                        WINDOW_HEIGHT / height - 36);
                BLK[i][j].setBackground(Color.BLUE);
                BLK[i][j].setForeground(Color.YELLOW);
                BLK[i][j].setBorder(BorderFactory.createRaisedBevelBorder());
                BLK[i][j].setFont(new Font("DejaVu Serif", Font.BOLD, 32));
                
            }
        }
        JBox board =
                JBox.vbox(
                        JBox.hbox(categories[0],categories[1],categories[2],categories[3],categories[4],categories[5]),
                        JBox.hbox(BLK[0][0], BLK[0][1], BLK[0][2], BLK[0][3],BLK[0][4], BLK[0][5]),
                        JBox.hbox(BLK[1][0], BLK[1][1], BLK[1][2], BLK[1][3],BLK[1][4], BLK[1][5]),
                        JBox.hbox(BLK[2][0], BLK[2][1], BLK[2][2], BLK[2][3],BLK[2][4], BLK[2][5]),
                        JBox.hbox(BLK[3][0], BLK[3][1], BLK[3][2], BLK[3][3],BLK[3][4], BLK[3][5]),
                        JBox.hbox(BLK[4][0], BLK[4][1], BLK[4][2], BLK[4][3],BLK[4][4], BLK[4][5]),
                        JBox.hbox(BLK[5][0], BLK[5][1], BLK[5][2], BLK[5][3],BLK[5][4], BLK[5][5])
                );
        board.setSize(WINDOW_WIDTH - 20, WINDOW_HEIGHT);
        frame.add(board);
        frame.setVisible(true);

        //Read file
        final BufferedReader reader = new BufferedReader(new FileReader("Question.txt"));
        final ArrayList<String> lines = new ArrayList<String>();
        String s;
        String S;
        S="";
        while ((s = reader.readLine()) != null) {
            S=S+s;
        }
        reader.close();
        
        for ( int i = 0; i < height; i++) {
            l=S.indexOf(Chapter[i]);
            if(i<5)
            {
                m=S.indexOf(Chapter[i+1]);
                Section=S.substring(l,m);
            }
            else
            {
                Section=S.substring(l,S.length());
            }
            for (int  j = 0; j < width; j++) {
                l=Section.indexOf(String.valueOf(j+1)+". ");
                m=Section.indexOf("a. ",1);
                Qestio=Section.substring(l+3, m);
                Question[i][j]=Qestio;
                Section=Section.substring(m,Section.length());
                
                n=Section.indexOf("()",1);
                Answe=Section.substring(2,n);
                Answer[i][j]=Answe;
            }
        }
        for ( int i = 0; i < height; i++) {
            for (int  j = 0; j < width; j++) {
                String cd=Question[i][j];
                String ab=Answer[i][j];
                BLK[i][j].addActionListener(new ActionListener() {
                    @Override

                    public void actionPerformed(ActionEvent e) {
                        String your_answer = JOptionPane.showInputDialog(cd);
                        JOptionPane.showMessageDialog(null, "Reference and yours: "+ ab +" Vs " + your_answer);
                        JButton source = (JButton) e.getSource();
                        source.setEnabled(false);
                        source.setBackground(Color.GREEN);
                    }
                });
            }
        }
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
}
// PUT YOUR METHODS HERE
    
    
//    public static void Readfile() throws IOException {
//        ArrayList<String> quotes = new ArrayList<String>();
//        BufferedReader readFile = new BufferedReader(new FileReader("Question.txt"));
//        String line = "";
//    }
//    
//    public static void ButtonArray(){
//        JButton[][] buttons = new JButton[6][6];
//        
//        for(int i = 0; i < buttons.length; i++){
//            for(int j=0; j<buttons[i].length; j++){
//                buttons[i][j] = new JButton("Button [" + i + "][" + j + "]");
//            }
//        }
//    }
//    
//    public static boolean Answer(boolean Aw){
//       return Aw; 
//    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
